# GitHub Action for Astro Website Release Sync
# This workflow automatically syncs new WeighMyBru² releases to your Astro website

name: Sync WeighMyBru² Release to Website

on:
  # Trigger when WeighMyBru² releases a new version
  repository_dispatch:
    types: [weighmybru_release]
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to sync (e.g., v2.1.0)'
        required: false
        default: 'latest'

jobs:
  sync-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout website repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq unzip
    
    - name: Sync WeighMyBru² Release
      env:
        GITHUB_REPO: "031devstudios/weighmybru2"
        WEBSITE_RELEASES_DIR: "./public/releases"
      run: |
        #!/bin/bash
        set -e
        
        echo "🚀 Starting WeighMyBru² release sync..."
        
        # Create releases directory
        mkdir -p "$WEBSITE_RELEASES_DIR"
        
        # Get latest release info
        echo "📡 Fetching latest release information..."
        RELEASE_INFO=$(curl -s "https://api.github.com/repos/$GITHUB_REPO/releases/latest")
        TAG_NAME=$(echo "$RELEASE_INFO" | jq -r '.tag_name')
        
        if [ "$TAG_NAME" = "null" ]; then
          echo "❌ No releases found"
          exit 1
        fi
        
        echo "📦 Found release: $TAG_NAME"
        
        # Create release directory
        RELEASE_DIR="$WEBSITE_RELEASES_DIR/$TAG_NAME"
        mkdir -p "$RELEASE_DIR"
        
        # Download assets
        echo "⬇️ Downloading release assets..."
        DOWNLOAD_URLS=$(echo "$RELEASE_INFO" | jq -r '.assets[].browser_download_url')
        
        while IFS= read -r url; do
          if [ -n "$url" ]; then
            FILENAME=$(basename "$url")
            echo "  Downloading $FILENAME..."
            curl -L -o "$RELEASE_DIR/$FILENAME" "$url"
          fi
        done <<< "$DOWNLOAD_URLS"
        
        # Extract firmware files
        echo "📂 Extracting firmware files..."
        for zip_file in "$RELEASE_DIR"/*.zip; do
          if [ -f "$zip_file" ]; then
            unzip -o "$zip_file" -d "$RELEASE_DIR/"
            rm "$zip_file"
          fi
        done
        
        # Update latest symlink
        echo "🔗 Updating latest release pointer..."
        LATEST_DIR="$WEBSITE_RELEASES_DIR/latest"
        rm -rf "$LATEST_DIR"
        
        # Copy instead of symlink for better compatibility
        mkdir -p "$LATEST_DIR"
        cp -r "$RELEASE_DIR"/* "$LATEST_DIR/"
        
        # Generate release index
        echo "📋 Generating release index..."
        cat > "$WEBSITE_RELEASES_DIR/index.json" << EOF
        {
          "latest": "$TAG_NAME",
          "last_updated": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
          "releases": [$(find "$WEBSITE_RELEASES_DIR" -maxdepth 1 -type d -name "v*" | sort -V | sed 's|.*/||' | sed 's/.*/"&"/' | paste -sd,)]
        }
        EOF
        
        # Validate manifests
        echo "✅ Validating ESP32 Web Tools manifests..."
        for manifest in "$LATEST_DIR"/manifest-*.json; do
          if [ -f "$manifest" ]; then
            if jq . "$manifest" > /dev/null 2>&1; then
              echo "  ✅ Valid: $(basename "$manifest")"
            else
              echo "  ❌ Invalid: $(basename "$manifest")"
              exit 1
            fi
          fi
        done
        
        echo "🎉 Successfully synced release $TAG_NAME!"
        
        # Output summary
        echo "📊 Release Summary:"
        echo "  Version: $TAG_NAME"
        echo "  Files: $(ls -1 "$LATEST_DIR" | wc -l)"
        echo "  Size: $(du -sh "$RELEASE_DIR" | cut -f1)"
    
    - name: Build Astro Website
      run: |
        npm install
        npm run build
    
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: your-project-name  # Replace with your Cloudflare Pages project name
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Notify Discord
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        TAG_NAME: ${{ env.TAG_NAME }}
      run: |
        if [ -n "$DISCORD_WEBHOOK" ]; then
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"🚀 **WeighMyBru² Release Sync Complete!**\\n\\n📦 **Version:** \`$TAG_NAME\`\\n🌐 **Website:** Updated with latest firmware\\n⚡ **Status:** Ready for web-based flashing!\"}" \
               "$DISCORD_WEBHOOK"
        fi
    
    - name: Create Pull Request (Optional)
      if: github.event_name == 'repository_dispatch'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🚀 Sync WeighMyBru² release ${{ env.TAG_NAME }}"
        title: "Sync WeighMyBru² release ${{ env.TAG_NAME }}"
        body: |
          ## 🚀 WeighMyBru² Release Sync
          
          This PR automatically syncs the latest WeighMyBru² firmware release to the website.
          
          ### 📦 Release Details
          - **Version:** ${{ env.TAG_NAME }}
          - **Source:** [GitHub Release](https://github.com/031devstudios/weighmybru2/releases/tag/${{ env.TAG_NAME }})
          - **Files:** ESP32 Web Tools manifests and firmware binaries
          
          ### ✅ What's Updated
          - Updated `/public/releases/latest/` with new firmware files
          - Generated ESP32 Web Tools manifests for both board variants
          - Updated release index for version tracking
          
          ### 🧪 Testing
          - [ ] ESP32 Web Tools manifests validated
          - [ ] Firmware files accessible via web
          - [ ] Website builds successfully
          
          Ready to merge once validated! 🎉
        branch: sync-weighmybru-${{ env.TAG_NAME }}
        delete-branch: true