#pragma once

static const uint8_t SCREEN_WIDTH = 128;
static const uint8_t SCREEN_HEIGHT = 32;

#define DISPLAY_CONTROLLER_SSD1306 1
#define DISPLAY_CONTROLLER_SH1106  2

#ifndef DISPLAY_CONTROLLER
#define DISPLAY_CONTROLLER DISPLAY_CONTROLLER_SSD1306
#endif